### ISSUE TITLE
 Allow defining types that extend another type #3 

### ISSUE THREAD

**Issue by NiklasRosenstein** [NiklasRosenstein/cytonic#1]
Example

```yml
  TokenInfo:
    fields:
      id: {type: string}
      type: {type: TokenType}
      revoked: {type: boolean}
      issue_date: {type: datetime}
      expiry_date: {type: datetime}
      scope: {type: 'optional[TokenScope]'}
  TokenResponse:
    extends: TokenInfo
    fields:
      access_token: {type: string}
```
